### ISSUE TITLE
mvn tomcat7:redeploy fails on vagrant

### ISSUE THREAD

**Issue by SebastinSanty** [prasadtalasila/BITS-Darshini#65]
Initial deployment using `mvn tomcat7:deploy` deploys the application correctly. On doing `mvn tomcat7:redeploy`, there is an error: 
```
Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:deploy (default-cli) on project protocolanalyzer: Cannot invoke Tomcat manager: The target server failed to respond -> [Help 1]
```

**Comment by SebastinSanty** [comment]
Just to take note: This is most probably due to insufficient memory allotted to vagrant by default (512MB). Increasing it to 4096 MB, doesn't show this error.

**Comment by prasadtalasila** [comment]
Then let's explicitly specify the VM memory to 4GB and close the issue.

**Comment by SebastinSanty** [comment]
On restarting the tomcat, redeploy works perfectly fine. Without restart, I guess tomcat runs into its own memory problems, which we need to configure manually.

This error comes:  ["Error invoking method check"](http://stackoverflow.com/questions/1536364/error-invoking-method-check-when-deploying-a-war-on-tomcat). Which hints at tomcat running out of memory. Check [this](http://www.mkyong.com/tomcat/tomcat-javalangoutofmemoryerror-permgen-space)

**Comment by anurag-rai** [comment]
I'm not sure if this is a memory issue. I have the same problem, but a different error:

> Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:redeploy (default-cli) on project protocolanalyzer: Cannot invoke Tomcat manager: Connection refused

**Comment by SebastinSanty** [comment]
What I have figured out, is that all the tomcat errors are related to memory issues in vagrant and tomcat. My upcoming commit should solve this issue. @anurag-rai : Is the vagrant working for you? (not considering the redeploy part)

**Comment by anurag-rai** [comment]
It worked for the first `deploy` after installation. After that I'm rather stuck as I can't `redeploy` or deploy again.

**Comment by SebastinSanty** [comment]
The latest commit on master branch should solve the issue. Can you try doing `vagrant halt` and then `vagrant up`?

**Comment by anurag-rai** [comment]
Tried. That didn't solve it. My error doesn't look like a memory problem.

**Comment by SebastinSanty** [comment]
Following the below mentioned sequence of commands, seems like the way to go for now
```
$ sudo rm -rf /var/lib/tomcat7/webapps/protocolanalyzer.war /var/lib/tomcat7/webapps/protocolanalyzer
$ sudo service tomcat7 restart
$ mvn tomcat7:deploy
```
@anurag-rai Can you confirm this, please?

**Comment by prasadtalasila** [comment]
scripts/redeploy.sh solves the problem. The vagrant VM must have atleast three virtual CPUs and 4GB RAM.
